Library/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using NuGet.Protocol.Plugins;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Cryptography;
using System.Data.SqlClient;
using System.Text.Encodings;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text;
using System.Net;
using System.Text.Json;
using Library.Models;
using Library.Services;
using Library.Authorization;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;


namespace Library.Controllers
{
    //[ApiController]
    //[Route("[controller]")]
    
    public class LoginController : Controller
    {

        /*private IAccountService _accountService;

        public LoginController(IAccountService userService)
        {
            _accountService = userService;
        }*/

        private IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        //[HttpGet("Authenticate")]
        [HttpGet]
        public IActionResult Authenticate()
        {
            return View();
        }

        // POST: Login
        //[HttpPost("Authenticate")]
        [HttpPost]
        [AllowAnonymous]
        public IActionResult Authenticate(AuthenticateRequest account)
        {
            /*if (account.Username != null && account.Password != null)
            {
                //var loginAccount = from s in _context.Accounts.Where(s => s.Username == account.Username) select s;
                var conn = new SqlConnection("Server=HOANG-ANH-VU;Database=TutorialDb;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=true");
                conn.Open();

                SqlCommand cmd2 = new SqlCommand("SELECT Password FROM dbo.Accounts WHERE Username='" + account.Username + "';", conn);
                string stringPass = (String)cmd2.ExecuteScalar();


                byte[] salt= Encoding.UTF8.GetBytes(account.Username);
                Console.WriteLine($"Salt: {Convert.ToBase64String(salt)}");

                var hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: account.Password!,
                    salt: salt,
                    prf: KeyDerivationPrf.HMACSHA256,
                    iterationCount: 100000,
                    numBytesRequested: 256 / 8));


                if (hashed==stringPass)
                {
                    //var response= _accountService.Authenticate(account);
                    return Redirect("Home");
                }
                ModelState.AddModelError(nameof(account.Password), "Login Failed: Invalid Username or Password");

            }
            return View(account);*/
            string myHostUrl = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            //Console.WriteLine(myHostUrl);
            //string myHostUrl = "https://localhost:4450";
            string apiUrl = $"{myHostUrl}/api/Users";
            string jsonString = System.Text.Json.JsonSerializer.Serialize(account);
            WebClient client = new WebClient();
            client.Headers["Content-type"] = "application/json";
            client.Encoding = Encoding.UTF8;
            string json = client.UploadString($"{apiUrl}/Authenticate", jsonString);
            //var details = JObject.Parse(json);
            var result = JsonConvert.DeserializeObject<AuthenticateResponseX>(json);
            if (json == "")
            {
                ModelState.AddModelError(nameof(account.Password), "Đăng nhập thất bại: Sai tên đăng nhập hoặc mật khẩu");
                return View(account);
            }

            var cookieOptions = new CookieOptions
            {
                HttpOnly = true,
                Expires = DateTime.UtcNow.AddDays(7)
            };
            //Console.WriteLine(details);
            Response.Cookies.Append("Authorization", result.JwtToken, cookieOptions);
            Response.Cookies.Append("refreshToken", result.RefreshToken, cookieOptions);

            HttpContext.Session.SetString("Role", result.Role);
            //HttpContext.Session["LoginName"] = result.Username;

            //return Ok(new { message = "Registration successful" });
            return RedirectToAction("Index", "Home");
        }

        private string ipAddress()
        {
            // get source ip address for the current request
            if (Request.Headers.ContainsKey("X-Forwarded-For"))
                return Request.Headers["X-Forwarded-For"];
            else
                return HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString();
        }
        /*private bool LoginExists(int id)
        {
            return (_context.Accounts?.Any(e => e.AccountID == id)).GetValueOrDefault();
        }*/
    }
}

Library/Controllers/YourController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Library.Authorization;
using Library.Data;
using Library.Services;
using AutoMapper.Configuration.Conventions;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using System.Runtime.Intrinsics.Arm;
using NuGet.Common;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.AspNet.Identity;

namespace Library.Controllers
{
    public class YourController : Controller
    {
        private readonly LibraryContext _context;

        public YourController(LibraryContext context)
        {
            _context = context;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(int? page, string searchbook, string? currentFilter, List<Genre> Genre, int[] idG, List<Author> Author, int[] idA, List<Year> Year, int[] idY, List<Publisher> Publisher, int[] idP,string selectSort)
        {

            if (selectSort == null) selectSort = ViewBag.Sort;
            if (searchbook != null) page = 1;
            else searchbook = currentFilter;

            ViewBag.CurrentFilter = searchbook;

            var token = Request.Cookies["RefreshToken"];

            var user = _context.Users.SingleOrDefault(u => u.RefreshTokens.Any(t => t.Token == token));
            var books = from book in _context.Books select book;

            if (user != null)
            {
                books = books.Where(book => book.UserId == user.UserId);
            }
            else books = books.Where(book => book.UserId == 0);



            if (!String.IsNullOrEmpty(searchbook))
            {
                books = books.Where(book => book.Title.Contains(searchbook));
            }
            if (books != null)
            {
                if (selectSort == "titleAscend") books = books.OrderBy(book => book.Title);
                else if (selectSort == "titleDescend") books = books.OrderByDescending(book => book.Title);
                else if (selectSort == "authorAscend") books = books.OrderBy(book => book.Author);
                else if (selectSort == "authorDescend") books = books.OrderByDescending(book => book.Author);
                else if (selectSort == "yearAscend") books = books.OrderBy(book => book.ReleaseYear);
                else if (selectSort == "yearDescend") books = books.OrderByDescending(book => book.ReleaseYear);
                else if (selectSort == "default") books = books.OrderBy(book => book.Id);
            }

            ViewBag.Sort = selectSort;

            IQueryable<Genre> genres = from genre in _context.Genres select genre;
            IQueryable<Author> authors = from author in _context.Authors select author;
            IQueryable<Year> years = from year in _context.Years select year;
            IQueryable<Publisher> publishers = from publisher in _context.Publishers select publisher;



            ViewBag.i = 0;
            ViewBag.pageSize = 5;
            var allFilter = new AllFilter
            {
                //Grade = new SelectList(await (from m in enrollmentQuery select m.Grade).Distinct().ToListAsync()),
                //Title = new SelectList(await (from m in courseQuery select m.Title).Distinct().ToListAsync()),
                PaginatedList = await PaginatedList<Book>.CreateAsync(books, page ?? 1, ViewBag.pageSize),
                Genre = genres.ToList(),
                Author = authors.ToList(),
                Year = years.ToList(),
                Publisher = publishers.ToList(),
                Username = (user!=null)?user.Username:"",
            };



            return View(allFilter);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Index(int? page, string searchbook, string? currentFilter, List<Genre> Genre, int[] idG, List<Author> Author, int[] idA, List<Year> Year, int[] idY, List<Publisher> Publisher, int[] idP, string selectSort, string selectOption)
        {
            if (selectSort == null) selectSort = ViewBag.Sort;
            if (selectOption == null) selectOption = ViewBag.Option;
            if (searchbook != null) page = 1;
            else searchbook = currentFilter;
            ViewBag.CurrentFilter = searchbook;

            var token = Request.Cookies["RefreshToken"];

            var user = _context.Users.SingleOrDefault(u => u.RefreshTokens.Any(t => t.Token == token));



            var books = from book in _context.Books select book;
            books = books.Where(book => book.UserId == user.UserId);


            if(!String.IsNullOrEmpty(searchbook))
            {
                if (selectOption == "quick") books = books.Where(book => (book.Title.Contains(searchbook) || book.Author.Contains(searchbook)
                || book.Genre.Contains(searchbook) || book.ISBN.Contains(searchbook) || book.ReleaseYear.Contains(searchbook)
                ));
                else if (selectOption == "title") books = books.Where(book => book.Title.Contains(searchbook));
                else if (selectOption == "author") books = books.Where(book => book.Author.Contains(searchbook));
                else if (selectOption == "genre") books = books.Where(book => book.Genre.Contains(searchbook));
                else if (selectOption == "isbn") books = books.Where(book => book.ISBN.Contains(searchbook));
                else if (selectOption == "yearpub") books = books.Where(book => book.ReleaseYear.Contains(searchbook));
            }

            if (idG.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Genre)
                {
                    if (idG.Length == j) break;
                    if (item.GenreId == idG[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.Genre.Contains(item.Vietnamese));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }

            if (idA.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Author)
                {
                    if (idA.Length == j) break;
                    if (item.AuthorId == idA[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.Author.Contains(item.Authors));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }

            if (idY.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Year)
                {
                    if (idY.Length == j) break;
                    if (item.YearId == idY[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.ReleaseYear.Contains(item.Years));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }

            if (idP.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Publisher)
                {
                    if (idP.Length == j) break;
                    if (item.PublisherId == idP[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.Publishing.Contains(item.Publishers));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }

            if (books != null)
            {
                if (selectSort == "titleAscend") books = books.OrderBy(book => book.Title);
                else if (selectSort == "titleDescend") books = books.OrderByDescending(book => book.Title);
                else if (selectSort == "authorAscend") books = books.OrderBy(book => book.Author);
                else if (selectSort == "authorDescend") books = books.OrderByDescending(book => book.Author);
                else if (selectSort == "yearAscend") books = books.OrderBy(book => book.ReleaseYear);
                else if (selectSort == "yearDescend") books = books.OrderByDescending(book => book.ReleaseYear);
                else if (selectSort == "default") books = books.OrderBy(book => book.Id);
            }
            ViewBag.Sort = selectSort;
            ViewBag.Option = selectOption;
            ViewBag.idG = idG;
            ViewBag.idA = idA;
            ViewBag.idY = idY;
            ViewBag.idP = idP;

            IQueryable<Genre> genres = from genre in _context.Genres select genre;
            IQueryable<Author> authors = from author in _context.Authors select author;
            IQueryable<Year> years = from year in _context.Years select year;
            IQueryable<Publisher> publishers = from publisher in _context.Publishers select publisher;

            ViewBag.i = 0;
            ViewBag.pageSize = 5;
            var allFilter = new AllFilter
            {
                //Grade = new SelectList(await (from m in enrollmentQuery select m.Grade).Distinct().ToListAsync()),
                //Title = new SelectList(await (from m in courseQuery select m.Title).Distinct().ToListAsync()),
                PaginatedList = await PaginatedList<Book>.CreateAsync(books, page ?? 1, ViewBag.pageSize),
                Genre = genres.ToList(),
                Author = authors.ToList(),
                Year = years.ToList(),

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/typicons/typicons.css">
    <link rel="stylesheet" href="~/lib/mdi/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="~/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/lib/vertical-layout-light/style.css">
</head>

<body style="border:5px;">
    <header>
        <nav class="navbar navbar-menu-wrapper navbar-expand-sm navbar-toggleable-sm bg-white border-bottom box-shadow mb-3 flex-row">
            <div class="container-fluid navbar-nav">
                <img src="~/picture/logo.png" height="30" width="50" alt="MDN" />
                <a id="navbar-brand" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Thư viện Tp. Hồ Chí Minh</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li id="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="mdi mdi-home-variant"></i>
                                <span style="white-space: pre;">  </span>
                                <span class="menu-title">Trang chủ</span>
                            </a>
                        </li>
                        <li id="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">
                                <i class="mdi mdi-theater"></i>
                                <span style="white-space: pre;">  </span>
                                <span class="menu-title">Giới thiệu</span>
                            </a>
                        </li>
                        <li id="nav-item">
                            @{
                                var search= await Component.InvokeAsync("Layout","search");
                            }
                            @search
                        </li>
                        <li id="nav-item">
                            @{

                                var book = await Component.InvokeAsync("Layout", "employee");
                            }
                            @book
                        </li>
                    </ul>
                     @*@{
                        @inject IHttpContextAccessor HttpContextAccessor

                        var role=HttpContextAccessor.HttpContext.Session.GetString("Role");
                        if (role == "Adminstrator")
                        {
                            <div id="nav_item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Add" asp-action="Index" style="text-align: right;">Thêm sách</a>
                            </div>
                        }
                    }*@
                    <ul class="navbar-nav navbar-nav-right">
                        <li id="nav-item">
                            @{

                                var verification = await Component.InvokeAsync("Layout", "verification");
                            }
                            @verification
                        </li>
                        @*<li id="nav-item">
                            @{

                                var addbook = await Component.InvokeAsync("Layout", "addbook");
                            }
                            @addbook
                        </li>*@
                        <li id="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Your" asp-action="Index">
                                <i class="mdi mdi-archive"></i>
                                <span style="white-space: pre;">  </span>
                                <span class="menu-title">Sách của bạn</span>
                            </a>
                        </li>
                        <li id="nav-item" class="btn-group nav-item dropdown" style="font-size: 0.875rem; box-shadow: 0 5px 10px 0 rgba(230, 230, 243, 0.88);
                            border: 1px solid #e4e4f4; margin-left: 0.531rem; margin-right: 0.531rem; border-radius:10px; ">

                            <button type="button" class="btn dropdown-toggle dropdown-toggle-split nav-item" id="dropdownMenuSplitButton1 nav-item" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding: 0.5rem 1rem;">
                                @{
                                    @*@inject IHttpContextAccessor HttpContextAccessor*@
                                   
                                    //var username = "Đăng nhập";
                                    //var refreshToekn = Context.Request.Cookies["refreshToken"];

                                    //var user = LibraryContext.Users.SingleOrDefault(u => u.RefreshTokens.Any(t => t.Token == token));

                                    //var refreshToken = Context.Request.Cookies["refreshToken"];

                                    //var username = Context.Request.Cookies["Username"];
                                    //if (username == null) username = "Đăng nhập
                                    var username = await Component.InvokeAsync("Layout", "username");
                                }
                                @{
                                    var iconAdmin = await Component.InvokeAsync("Layout", "iconAdmin");
                                }
                                @iconAdmin
                                <span style="white-space: pre;">  </span>
                                @username
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="dropdownMenuSplitButton1" style="border-radius:10px;">
                                <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Authenticate">Đăng nhập</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Register" asp-action="Register">Đăng ký</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout">Đăng xuất</a>
                            </div>
                         
                        </li>
                        <li id="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Your" asp-action="Index" style="text-align: right;"><i class="typcn typcn-bell mx-0"></i></i></a>
                        </li>
                        <li id="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Your" asp-action="Index" style="text-align: right;"><i class="typcn typcn-cog-outline mx-0"></i></i></a>
                        </li>
                    </ul>
                    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                        <span class="typcn typcn-th-menu"></span>
                    </button>
                   
                    
                    </div>
                </div>
            </div>
        </nav>

    

    </header>
    <div class="container">
        <main role="main" class="pb-3" >
            
            @RenderBody()
        </main>
    </div>
    
    <center>
        <footer id="bottom-foot" class="border-top footer text-muted">
            <div class="bottom-text">
                &copy; <span class="theyear"></span> - Thư viện Tp. Hồ Chí Minh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Điều khoản</a>
            </div>
            <div class="linkage"> </div>
        </footer>
    </center>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/vendor.bundle.base.js"></script>
    <script src="~/js/off-canvas.js"></script>
    <script src="@Url.Content("~/js/layout.js")"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Library/Views/Shared/_NavPartial.cshtml
<!-- partial:partials/_settings-panel.html -->
<!-- partial -->
<!-- partial:partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar" style="border-radius:10px;">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="mdi mdi-home-variant"></i>
                <span style="white-space: pre;">  </span>
                <span class="menu-title">Trang chủ</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">
                <i class="mdi mdi-theater"></i>
                <span style="white-space: pre;">  </span>
                <span class="menu-title">Giới thiệu</span>
            </a>


        </li>
        <li class="nav-item">
            @{
                var search = await Component.InvokeAsync("Layout", "search");
            }
            @search
        </li>
        <li class="nav-item">
            @{
                var book = await Component.InvokeAsync("Layout", "employee");
            }
            @book
        </li>
        <li class="nav-item">
            @{

                var verification = await Component.InvokeAsync("Layout", "verification");
            }
            @verification
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Your" asp-action="Index">
                <i class="mdi mdi-archive"></i>
                <span style="white-space: pre;">  </span>
                <span class="menu-title">Sách của bạn</span>
            </a>
        </li>
    </ul>
</nav>
<!-- partial -->