Library/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using NuGet.Protocol.Plugins;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Cryptography;
using System.Data.SqlClient;
using System.Text.Encodings;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Text;
using System.Net;
using System.Text.Json;
using Library.Models;
using Library.Services;
using Library.Authorization;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;


namespace Library.Controllers
{
    //[ApiController]
    //[Route("[controller]")]
    
    public class LoginController : Controller
    {

        /*private IAccountService _accountService;

        public LoginController(IAccountService userService)
        {
            _accountService = userService;
        }*/

        private IUserService _userService;

        public LoginController(IUserService userService)
        {
            _userService = userService;
        }

        //[HttpGet("Authenticate")]
        [HttpGet]
        public IActionResult Authenticate()
        {
            return View();
        }

        // POST: Login
        //[HttpPost("Authenticate")]
        [HttpPost]
        [AllowAnonymous]
        public IActionResult Authenticate(AuthenticateRequest account)
        {
            /*if (account.Username != null && account.Password != null)
            {
                //var loginAccount = from s in _context.Accounts.Where(s => s.Username == account.Username) select s;
                var conn = new SqlConnection("Server=HOANG-ANH-VU;Database=TutorialDb;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=true");
                conn.Open();

                SqlCommand cmd2 = new SqlCommand("SELECT Password FROM dbo.Accounts WHERE Username='" + account.Username + "';", conn);
                string stringPass = (String)cmd2.ExecuteScalar();


                byte[] salt= Encoding.UTF8.GetBytes(account.Username);
                Console.WriteLine($"Salt: {Convert.ToBase64String(salt)}");

                var hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: account.Password!,
                    salt: salt,
                    prf: KeyDerivationPrf.HMACSHA256,
                    iterationCount: 100000,
                    numBytesRequested: 256 / 8));


                if (hashed==stringPass)
                {
                    //var response= _accountService.Authenticate(account);
                    return Redirect("Home");
                }
                ModelState.AddModelError(nameof(account.Password), "Login Failed: Invalid Username or Password");

            }
            return View(account);*/
            string myHostUrl = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            //Console.WriteLine(myHostUrl);
            //string myHostUrl = "https://localhost:4450";
            string apiUrl = $"{myHostUrl}/api/Users";
            string jsonString = System.Text.Json.JsonSerializer.Serialize(account);
            WebClient client = new WebClient();
            client.Headers["Content-type"] = "application/json";
            client.Encoding = Encoding.UTF8;
            string json = client.UploadString($"{apiUrl}/Authenticate", jsonString);
            //var details = JObject.Parse(json);
            var result = JsonConvert.DeserializeObject<AuthenticateResponseX>(json);
            if (json == "")
            {
                ModelState.AddModelError(nameof(account.Password), "Đăng nhập thất bại: Sai tên đăng nhập hoặc mật khẩu");
                return View(account);
            }

            var cookieOptions = new CookieOptions
            {
                HttpOnly = true,
                Expires = DateTime.UtcNow.AddDays(7)
            };
            //Console.WriteLine(details);
            Response.Cookies.Append("Authorization", result.JwtToken, cookieOptions);
            Response.Cookies.Append("refreshToken", result.RefreshToken, cookieOptions);

            HttpContext.Session.SetString("Role", result.Role);
            //HttpContext.Session["LoginName"] = result.Username;

            //return Ok(new { message = "Registration successful" });
            return RedirectToAction("Index", "Home");
        }

        private string ipAddress()
        {
            // get source ip address for the current request
            if (Request.Headers.ContainsKey("X-Forwarded-For"))
                return Request.Headers["X-Forwarded-For"];
            else
                return HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString();
        }
        /*private bool LoginExists(int id)
        {
            return (_context.Accounts?.Any(e => e.AccountID == id)).GetValueOrDefault();
        }*/
    }
}

Library/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNet.Identity;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Text;
using Library.Models;
using Library.Authorization;
using Library.Services;
using Microsoft.AspNetCore.Http.Extensions;
using System.Text.Json;
using System.Net.Http;
using Microsoft.Extensions.Hosting;
using System.Net;
using Newtonsoft.Json;

namespace Library.Controllers
{

    //[Authorize]
    public class RegisterController : Controller
    {
        /*private readonly ContosoUniversityContext _context;

        public RegisterController(ContosoUniversityContext context)
        {
            _context = context;
        }*/

        private IUserService _userService;

        public RegisterController(IUserService userService)
        {
            _userService = userService;
        }

        // GET: Login
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Register()
        {
            
            return View();
        }

        // POST: Login
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequest account)
        {
            /*if( account.Username != null && account.Password != null)
            {
                byte[] salt = Encoding.UTF8.GetBytes(account.Username); ;
                var hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: account.Password!,
                    salt: salt,
                    prf: KeyDerivationPrf.HMACSHA256,
                    iterationCount: 100000,
                    numBytesRequested: 256 / 8));


                account.Password = hashed;
                account.Salt = salt;
                //var loginAccount = from s in _context.Accounts.Where(s => s.Username == account.Username && s.Password == account.Password) select s;
                _context.Add(account);
                await _context.SaveChangesAsync();
                return Redirect("Home");
            }
            ModelState.AddModelError(nameof(account.Password), "Register Failed: Invalid Username or Password");
            return View(account);*/
            String myHostUrl = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";
            //Console.Write(account);
            string apiUrl = $"{myHostUrl}/api/Users";
            Console.Write(apiUrl);
            string jsonString = System.Text.Json.JsonSerializer.Serialize(account);
            WebClient client = new WebClient();
            client.Headers["Content-type"] = "application/json";
            client.Encoding = Encoding.UTF8;
            string json = client.UploadString($"{apiUrl}/Register", jsonString);
            var result = JsonConvert.DeserializeObject<AuthenticateResponseX>(json);
            if (json == null)
            {
                return NotFound();
            }
            var cookieOptions = new CookieOptions
            {
                HttpOnly = true,
                Expires = DateTime.UtcNow.AddDays(7)
            };
            //Console.WriteLine(details);
            Response.Cookies.Append("Authorization", result.JwtToken, cookieOptions);
            Response.Cookies.Append("refreshToken", result.RefreshToken, cookieOptions);

            return RedirectToAction("Index", "Home");
            //_userService.Register(account);
            //Ok(new { message = "Registration successful" });
            //return Ok(new { message = "Registration successful" });

        }

        /*private bool AccountExists(int id)
        {
          return (_context.Accounts?.Any(e => e.AccountID == id)).GetValueOrDefault();
        }*/
    }


}

Library/Views/Register/Register.cshtml
@model Library.Models.RegisterRequest


@{
    ViewData["Title"] = "Đăng ký";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V2</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/login.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/user.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />

    <!--===============================================================================================-->
</head>
<body>
   

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <form class="login100-form validate-form" asp-controller="Register" asp-action="Register" method="post">
                    <span class="login100-form-title p-b-26">
                        Xin chào
                    </span>
                    <span class="login100-form-title p-b-48">
                        <img src="~/picture/logo.png" height="100" width="150" alt="MDN" />
                    </span>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="FirstName">
                        <span class="focus-input100" data-placeholder="Nhập tên"></span>
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="LastName">
                        <span class="focus-input100" data-placeholder="Nhập họ"></span>
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                    <div class="wrap-input100 validate-input">
                        <input class="input100" type="text" name="Username">
                        <span class="focus-input100" data-placeholder="Nhập tên đăng nhập"></span>
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Enter password">
                        <span class="btn-show-pass">
                            <i class="zmdi zmdi-eye"></i>
                        </span>
                        <input class="input100" type="password" name="Password">
                        <span class="focus-input100" data-placeholder="Nhập mật khẩu"></span>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="container-login100-form-btn">
                        <div class="wrap-login100-form-btn">
                            <div class="login100-form-bgbtn"></div>
                            <button class="login100-form-btn">
                                Đăng ký
                            </button>
                        </div>
                    </div>

                    <div class="text-center p-t-30">
                        <span class="txt1" style="font-size:17px;">
                            Đã có tài khoản? 
                        </span>

                        <a class="txt2" asp-area="" asp-controller="Login" asp-action="Authenticate" style="text-decoration:underline; font-size:17px;">
                            Đăng nhập
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div id="dropDownSelect1"></div>


    <!--===============================================================================================-->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <!--===============================================================================================-->
    <script src="~/lib/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/lib/bootstrap/js/popper.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/lib/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/lib/daterangepicker/moment.min.js"></script>
    <script src="~/lib/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/lib/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/js/login.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @section Scripts
    {
        <script src="@Url.Content("~/js/layout.js")"></script>
    }
    


</body>
</html>

@*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/user.css" asp-append-version="true" />
<link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />

@{
    ViewData["Title"] = "Index";
}

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Thư viện Tp. Hồ Chí Minh</a>
                <img src="~/picture/logo.jpg" height="20" width="20" alt="MDN" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Authenticate" style="text-align: right;"></a>
                        </li>
                    </ul>
                    <div class="nav_item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Authenticate" style="text-align: right;">
                            @{
                                @inject IHttpContextAccessor HttpContextAccessor

                                var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
                                if (username == null) username = "Đăng nhập";
                            }
                            @username
                        </a>
                    </div>
                    <div class="nav_item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index" style="text-align: right;">Đăng ký</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    

    <form asp-controller="Register" asp-action="Index" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <!--<input type="hidden" asp-for="AccountID" />-->
        <div class="imgcontainer">
            <img src="img_avatar2.png" alt="Avatar" class="avatar">
        </div>

        <div class="container">
        

            <label for="FirstName"><b>Tên</b></label>
            <input type="text" id="FirstName" placeholder="Nhập tên" name="FirstName" required>
            <span asp-validation-for="FirstName" class="text-danger"></span>

            <label for="LastName"><b>Họ</b></label>
            <input type="text" id="LastName"  placeholder="Nhập họ" name="LastName" required>
            <span asp-validation-for="LastName" class="text-danger"></span>

            <label for="Username"><b>Tên đăng nhập</b></label>
            <input type="text" id="Username" placeholder="Nhập tên đăng nhập" name="Username" required>
            <span asp-validation-for="Username" class="text-danger"></span>

            <label for="Password"><b>Mật khẩu</b></label>
            <input type="password" id="Password" placeholder="Nhập mật khẩu" name="Password" required>
            <span asp-validation-for="Password" class="text-danger"></span>

            
            <button type="submit" >Đăng ký</button>
            <!--<label>
                <input type="checkbox" checked="checked" name="remember"> Remember me
            </label> -->
        </div>

        <div class="container" style="background-color:#f1f1f1">
            <button type="button" class="cancelbtn">Cancel</button>
            <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
    </form>


    <div id="body">
        <section class="content-wrapper main-content clear-fix">
        </section>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Thư viện Tp. Hồ Chí Minh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Điều khoản</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script asp-append-version="true"></script>

</body>*@

@*<button id="submitBTN" class="submit" onclick="addItem()">Register</button>*@