Library/Controllers/AddEmployeeController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Library.Authorization;
using Library.Data;
using Library.Services;
using AutoMapper.Configuration.Conventions;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using System.Runtime.Intrinsics.Arm;
using System.Reflection;
using System.Data;
using static System.Reflection.Metadata.BlobBuilder;
using System.Security.Policy;
using System.Reflection.Metadata;

namespace Library.Controllers
{
    public class AddEmployeeController : Controller
    {
        private readonly LibraryContext _context;

        public AddEmployeeController(LibraryContext context)
        {
            _context = context;
        }

        //[AdminstratorAuthorize]
        [AdminstratorAuthorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        //[AdminstratorAuthorize]
        [AdminstratorAuthorize]
        [HttpPost]
        public async Task<IActionResult> Index([Bind("FirstName","LastName","Job","Image","Salary","Description")] Employee employee, IFormFile imgFile)
        {

            try
            {
                if (employee.FirstName != null && employee.LastName != null && employee.Job != null && employee.Salary != null && employee.Description != null && imgFile != null)
                {
                    byte[] p1 = null;
                    using (var fs1 = imgFile.OpenReadStream())
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                    employee.Image = Convert.ToBase64String(p1);
                    _context.Add(employee);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (DataException /* dex */ )
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View();
        }
    }
}

Library/Controllers/EmployeeController.cs
using Library.Authorization;
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Mvc;
namespace Library.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly LibraryContext _context;

        public EmployeeController(LibraryContext context)
        {
            _context = context;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(int? page, string searchEmployee, string? currentFilter, string selectSort)
        {

            if (selectSort == null) selectSort = ViewBag.Sort;
            if (searchEmployee != null) page = 1;
            else searchEmployee = currentFilter;

            ViewBag.CurrentFilter = searchEmployee;

            var token = Request.Cookies["RefreshToken"];

            var user = _context.Users.SingleOrDefault(u => u.RefreshTokens.Any(t => t.Token == token));
            var employees = from employee in _context.Employees select employee;



            if (employees != null)
            {
                if (selectSort == "LastNameAscend") employees = employees.OrderBy(book => book.LastName);
                else if (selectSort == "LastNameDescend") employees = employees.OrderByDescending(book => book.LastName);
                else if (selectSort == "FirstNameAscend") employees = employees.OrderBy(book => book.FirstName);
                else if (selectSort == "FirstNameDescend") employees = employees.OrderByDescending(book => book.FirstName);
                else if (selectSort == "JobAscend") employees = employees.OrderBy(book => book.Job);
                else if (selectSort == "JobDescend") employees = employees.OrderByDescending(book => book.Job);
                else if (selectSort == "default") employees = employees.OrderBy(book => book.EmployeeId);
            }

            ViewBag.Sort = selectSort;

            ViewBag.i = 0;
            ViewBag.pageSize = 5;


            return View(await PaginatedList<Employee>.CreateAsync(employees, page ?? 1, ViewBag.pageSize));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Index(int? page, string searchEmployee, string? currentFilter, string selectSort, string selectOption)
        {
            if (selectSort == null) selectSort = ViewBag.Sort;
            if (selectOption == null) selectOption = ViewBag.Option;
            if (searchEmployee != null) page = 1;
            else searchEmployee = currentFilter;
            ViewBag.CurrentFilter = searchEmployee;

            var token = Request.Cookies["RefreshToken"];

            var user = _context.Users.SingleOrDefault(u => u.RefreshTokens.Any(t => t.Token == token));



            var employees = from employee in _context.Employees select employee;


            if (!String.IsNullOrEmpty(searchEmployee))
            {
                if (selectOption == "quick") employees = employees.Where(book => book.FirstName.Contains(searchEmployee) || book.LastName.Contains(searchEmployee) || book.Job.Contains(searchEmployee));
                else if (selectOption == "name") employees = employees.Where(book => book.FirstName.Contains(searchEmployee) || book.LastName.Contains(searchEmployee));
                else if (selectOption == "job") employees = employees.Where(book => book.Job.Contains(searchEmployee));
            }


            if (employees != null)
            {
                if (selectSort == "LastNameAscend") employees = employees.OrderBy(book => book.LastName);
                else if (selectSort == "LastNameDescend") employees = employees.OrderByDescending(book => book.LastName);
                else if (selectSort == "FirstNameAscend") employees = employees.OrderBy(book => book.FirstName);
                else if (selectSort == "FirstNameDescend") employees = employees.OrderByDescending(book => book.FirstName);
                else if (selectSort == "JobAscend") employees = employees.OrderBy(book => book.Job);
                else if (selectSort == "JobDescend") employees = employees.OrderByDescending(book => book.Job);
                else if (selectSort == "default") employees = employees.OrderBy(book => book.EmployeeId);
            }
            ViewBag.Sort = selectSort;
            ViewBag.Option = selectOption;


            ViewBag.i = 0;
            ViewBag.pageSize = 5;


            return View(await PaginatedList<Employee>.CreateAsync(employees, page ?? 1, ViewBag.pageSize));
        }

        /*[Authorize]
        [HttpPost]
        public async Task<IActionResult> Return(int idbook)
        {
            //var books = from book in _context.books select book;
            var books = _context.books.SingleOrDefault(book => book.Id == idbook);
            if (books != null)
            {
                books.Status = null;
            }


            _context.SaveChanges();
            return Redirect("Index");
        }*/
    }
}

Library/Views/AddEmployee/Index.cshtml
@model Library.Models.AllFilter
@{
    ViewData["Title"] = "Thêm nhân viên";
}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>PolluxUI Admin</title>
<!-- base:css -->
<link rel="stylesheet" href="~/lib/typicons/typicons.css">
<link rel="stylesheet" href="~/css/vendor.bundle.base.css">
<link rel="stylesheet" href="~/css/change.css">
<!-- endinject -->
<!-- plugin css for this page -->
<link rel="stylesheet" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" href="~/lib/select2-bootstrap-theme/select2-bootstrap.min.css">
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="~/lib/vertical-layout-light/style.css">


<body>
    <div class="container-fluid page-body-wrapper">
        <partial name="_NavPartial" />
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="container-scroller">
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Thêm sách</h4>
                        <form class="form-sample" asp-action="Index" asp-controller="AddEmployee" method="post" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Họ</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="LastName" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Tên</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="FirstName" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Công việc</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="Job" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Lương</label>
                                        <div class="col-sm-9">
                                            <input class="form-control" name="Salary"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Đăng ảnh</label>
                                        <input type="file" name="imgFile" class="file-upload-default">
                                        <div class="input-group col-xs-12">
                                            <input type="text" name="imgFile" class="form-control file-upload-info" disabled placeholder="Đăng ảnh">
                                            <span class="input-group-append">
                                                <button class="file-upload-browse btn btn-primary" type="button" >Đăng</button>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <label class="card-description">
                                <strong>Đặc điểm</strong>
                            </label>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <div class="col-sm-12">
                                            <textarea class="form-control"  name="Description"  rows="5"></textarea>
                                        </div>
                                    </div>
                                </div>
                              
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Thêm</button>
                            <button class="btn btn-danger" asp-action="Index" asp-controller="Employee">Hủy bỏ</button>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
            </div>
        </div>
    </div>

    <script src="~/js/vendor.bundle.base.js"></script>
    <script src="~/js/file-upload.js"></script>
</body>
