Library/Controllers/AddBookController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Library.Authorization;
using Library.Data;
using Library.Services;
using AutoMapper.Configuration.Conventions;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using System.Runtime.Intrinsics.Arm;
using System.Reflection;
using System.Data;
using static System.Reflection.Metadata.BlobBuilder;
using System.Security.Policy;
using System.Reflection.Metadata;

namespace Library.Controllers
{
    public class AddBookController : Controller
    {
        private readonly LibraryContext _context;

        public AddBookController(LibraryContext context)
        {
            _context = context;
        }

        //[AdminstratorAuthorize]
        [AdminstratorAuthorize]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var genres = from genre in _context.Genres select genre;

            var allFilter = new AllFilter
            {
                //Grade = new SelectList(await (from m in enrollmentQuery select m.Grade).Distinct().ToListAsync()),
                //Title = new SelectList(await (from m in courseQuery select m.Title).Distinct().ToListAsync()),
                Genre = genres.ToList(),
            };



            return View(allFilter);
        }

        //[AdminstratorAuthorize]
        [AdminstratorAuthorize]
        [HttpPost]
        public async Task<IActionResult> Index([Bind("Title","Genre","Description","Author","Image", "ReleaseYear","Publishing","ISBN")]Book book,IFormFile imgFile)
        {

            try
            {
                if (book.Title!=null && book.Genre!=null && book.Description != null && book.Author != null && book.ReleaseYear != null && book.Publishing != null && book.ISBN != null && imgFile!=null)
                {
                    byte[] p1 = null;
                    using (var fs1 = imgFile.OpenReadStream())
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                    book.Image = Convert.ToBase64String(p1);
                    _context.Add(book);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (DataException /* dex */ )
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View();
        }
    }
}

Library/Controllers/SearchController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Library.Authorization;
using Library.Data;
using Library.Services;
using AutoMapper.Configuration.Conventions;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using System.Runtime.Intrinsics.Arm;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Razor;

namespace Library.Controllers
{
    public class SearchController : Controller
    {
        private readonly LibraryContext _libraryContext;
        private IUserService _userService;
        private IJwtUtils _jwtUtils;

        public SearchController(LibraryContext libraryContext,IUserService userService, IJwtUtils jwtUtils)
        {
            _libraryContext = libraryContext;
            _userService = userService;
            _jwtUtils = jwtUtils;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Index(int? page, string searchbook, string? currentFilter, List<Genre> Genre, int[] idG, List<Author> Author, int[] idA, List<Year> Year, int[] idY, List<Publisher> Publisher, int[] idP, string selectSort)
        {

            if (selectSort==null) selectSort=ViewBag.Sort;
            if (searchbook != null) page = 1;
            else searchbook = currentFilter;

            ViewBag.CurrentFilter = searchbook;

            var books = from book in _libraryContext.Books select book;
            if (!String.IsNullOrEmpty(searchbook))
            {
                books = books.Where(book => book.Title.Contains(searchbook));
            }

            if (books != null)
            {
                if (selectSort == "titleAscend") books = books.OrderBy(book=>book.Title);
                else if (selectSort == "titleDescend") books = books.OrderByDescending(book => book.Title);
                else if (selectSort == "authorAscend") books = books.OrderBy(book => book.Author);
                else if (selectSort == "authorDescend") books = books.OrderByDescending(book => book.Author);
                else if (selectSort == "yearAscend") books = books.OrderBy(book => book.ReleaseYear);
                else if (selectSort == "yearDescend") books = books.OrderByDescending(book => book.ReleaseYear);
                else if (selectSort == "default") books = books.OrderBy(book => book.Id);
            }
            ViewBag.Sort = selectSort;

            IQueryable<Genre> genres = from genre in _libraryContext.Genres select genre;
            IQueryable<Author> authors = from author in _libraryContext.Authors select author;
            IQueryable<Year> years = from year in _libraryContext.Years select year;
            IQueryable<Publisher> publishers = from publisher in _libraryContext.Publishers select publisher;


            ViewBag.i = 0;
            ViewBag.pageSize = 5;
            var allFilter = new AllFilter
            {
                //Grade = new SelectList(await (from m in enrollmentQuery select m.Grade).Distinct().ToListAsync()),
                //Title = new SelectList(await (from m in courseQuery select m.Title).Distinct().ToListAsync()),
                PaginatedList = await PaginatedList<Book>.CreateAsync(books, page ?? 1, ViewBag.pageSize),
                Genre = genres.ToList(),
                Author = authors.ToList(),
                Year = years.ToList(),
                Publisher = publishers.ToList(),
            };



            return View(allFilter);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Index(int? page, string searchbook,  string? currentFilter,List<Genre> Genre, int[] idG,List<Author> Author, int[] idA,List<Year> Year, int[] idY, List<Publisher> Publisher, int[] idP,string selectOption, string selectSort,string x)
        {
            if (selectSort == null) selectSort = ViewBag.Sort;
            if (selectOption == null) selectOption = ViewBag.Option;
            if (searchbook != null) page = 1;
            else searchbook = currentFilter;
            ViewBag.CurrentFilter = searchbook;

            var books = from book in _libraryContext.Books select book;
            if (!String.IsNullOrEmpty(searchbook))
            {
                if (selectOption == "quick") books = books.Where(book => (book.Title.Contains(searchbook) || book.Author.Contains(searchbook) 
                || book.Genre.Contains(searchbook) || book.ISBN.Contains(searchbook) || book.ReleaseYear.Contains(searchbook)
                ));
                else if (selectOption == "title") books = books.Where(book => book.Title.Contains(searchbook));
                else if (selectOption == "author") books = books.Where(book => book.Author.Contains(searchbook));
                else if (selectOption == "genre") books = books.Where(book => book.Genre.Contains(searchbook));
                else if (selectOption == "isbn") books = books.Where(book => book.ISBN.Contains(searchbook));
                else if (selectOption == "yearpub") books = books.Where(book => book.ReleaseYear.Contains(searchbook));
            }


            if (idG.Length>0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach(var item in Genre)
                {
                    if (idG.Length == j) break;
                    if (item.GenreId == idG[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.Genre.Contains(item.Vietnamese));
                    }
                }
                
                books = books.Except(booksX);
                //Console.WriteLine(a);
            }
            
            //ViewBag.Genre = Genre;


            if (idA.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Author)
                {
                    if (idA.Length == j) break;
                    if (item.AuthorId == idA[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.Author.Contains(item.Authors));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }
            

            if (idY.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Year)
                {
                    if (idY.Length == j) break;
                    if (item.YearId == idY[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.ReleaseYear.Contains(item.Years));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }

            

            if (idP.Length > 0)
            {
                var booksX = books;
                int j = 0;
                string[] a = { };
                foreach (var item in Publisher)
                {
                    if (idP.Length == j) break;
                    if (item.PublisherId == idP[j])
                    {
                        j++;
                        booksX = booksX.Where(book => !book.Publishing.Contains(item.Publishers));
                    }
                }

                books = books.Except(booksX);
                //Console.WriteLine(a);
            }

            if (books != null)
            {
                if (selectSort == "titleAscend") books = books.OrderBy(book => book.Title);
                else if (selectSort == "titleDescend") books = books.OrderByDescending(book => book.Title);
                else if (selectSort == "authorAscend") books = books.OrderBy(book => book.Author);
                else if (selectSort == "authorDescend") books = books.OrderByDescending(book => book.Author);
                else if (selectSort == "yearAscend") books = books.OrderBy(book => book.ReleaseYear);
                else if (selectSort == "yearDescend") books = books.OrderByDescending(book => book.ReleaseYear);
                else if (selectSort == "default") books = books.OrderBy(book => book.Id);
            }
            ViewBag.Sort = selectSort;
            ViewBag.Option = selectOption;
            ViewBag.idG = idG;
            ViewBag.idA = idA;
            ViewBag.idY = idY;
            ViewBag.idP = idP;

            IQueryable<Genre> genres = from genre in _libraryContext.Genres select genre;
            IQueryable<Author> authors = from author in _libraryContext.Authors select author;
            IQueryable<Year> years = from year in _libraryContext.Years select year;
            IQueryable<Publisher> publishers = from publisher in _libraryContext.Publishers select publisher;

            ViewBag.i = 0;
            ViewBag.pageSize = 5;
            var allFilter = new AllFilter
            {
                //Grade = new SelectList(await (from m in enrollmentQuery select m.Grade).Distinct().ToListAsync()),
                //Title = new SelectList(await (from m in courseQuery select m.Title).Distinct().ToListAsync()),
                PaginatedList = await PaginatedList<Book>.CreateAsync(books, page ?? 1, ViewBag.pageSize),
                Genre = genres.ToList(),
                Author = authors.ToList(),
                Year = years.ToList(),
                Publisher = publishers.ToList(),
            };



            return View(allFilter);
        }

        [AdminstratorAuthorize]
        [HttpGet]

Library/Views/AddBook/Index.cshtml
@model Library.Models.AllFilter
@{
    ViewData["Title"] = "Thêm sách";
}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>PolluxUI Admin</title>
<!-- base:css -->
<link rel="stylesheet" href="~/lib/typicons/typicons.css">
<link rel="stylesheet" href="~/css/vendor.bundle.base.css">
<link rel="stylesheet" href="~/css/change.css">
<!-- endinject -->
<!-- plugin css for this page -->
<link rel="stylesheet" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" href="~/lib/select2-bootstrap-theme/select2-bootstrap.min.css">
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="~/lib/vertical-layout-light/style.css">


<body>
    <div class="container-fluid page-body-wrapper">
        <partial name="_NavPartial" />
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="container-scroller" >
                    <div class="row">
                        <div class="col-12 grid-margin">
                            <div class="card">
                                <div class="card-body" style="border-radius: 10px !important;">
                                    <h4 class="card-title">Thêm sách</h4>
                                    <form class="form-sample" asp-action="Index" asp-controller="AddBook" method="post" enctype="multipart/form-data">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group row">
                                                    <label class="col-sm-3 col-form-label">Tên sách</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" class="form-control" name="Title" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group row">
                                                    <label class="col-sm-3 col-form-label">Thể loại</label>
                                                    <div class="col-sm-9">
                                                        <div class="select btn-lg">
                                                            <select id="cbSearchValueform-quick1" name="Genre" style="width:80%; font-size:20px;">
                                                                @{
                                                                    foreach (var item in Model.Genre)
                                                                    {
                                                                        <option value="@item.Vietnamese">@item.Vietnamese</option>
                                                                    }
                                                                }

                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group row">
                                                    <label class="col-sm-3 col-form-label">Tác giả</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" class="form-control" name="Author" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group row">
                                                    <label class="col-sm-3 col-form-label">Nhà xuất bản</label>
                                                    <div class="col-sm-9">
                                                        <input class="form-control" name="Publishing"/>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group row">
                                                    <label class="col-sm-3 col-form-label">Năm sản xuất</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" class="form-control" placeholder="yyyy" name="ReleaseYear"/>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group row">
                                                    <label class="col-sm-3 col-form-label">Mã số ISBN</label>
                                                    <div class="col-sm-9">
                                                        <input type="text" class="form-control" name="ISBN"/> 
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Đăng ảnh</label>
                                                    <input type="file" name="imgFile" class="file-upload-default">
                                                    <div class="input-group col-xs-12">
                                                        <input type="text" name="imgFile" class="form-control file-upload-info" disabled placeholder="Đăng ảnh">
                                                        <span class="input-group-append">
                                                            <button class="file-upload-browse btn btn-primary" type="button" >Đăng</button>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <label class="card-description">
                                            <strong>Mô tả</strong>
                                        </label>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group row">
                                                    <div class="col-sm-12">
                                                        <textarea class="form-control"  name="Description"  rows="5"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                              
                                        </div>
                                        <button type="submit" class="btn btn-primary mr-2" style="border-radius: 10px !important;">Thêm</button>
                                        <button class="btn btn-danger" asp-action="IndexAdmin" asp-controller="Search" style="border-radius: 10px !important;">Hủy bỏ</button>
                            
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/js/vendor.bundle.base.js"></script>
    <script src="~/js/file-upload.js"></script>
</body>
